pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/qapacker/todo-list-aws.git'
        BRANCH = 'master'
        PATH = "$PATH:/var/lib/jenkins/.local/bin"
    }

    stages {

        stage('Get Code') {
            steps {
                git branch: "${BRANCH}", url: "${REPO_URL}"
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    pip install --user aws-sam-cli
                    export PATH=$PATH:/var/lib/jenkins/.local/bin

                    sam build
                    sam deploy --config-env production \
                               --config-file samconfig.toml \
                               --no-confirm-changeset \
                               --no-fail-on-empty-changeset
                '''
            }
        }

        stage('Rest Test') {
            steps {
                sh '''
                    pip install --user pytest requests
                    export PATH=$PATH:/var/lib/jenkins/.local/bin

                    mkdir -p reports
                    # Ejecutar solo tests GET o de solo lectura (debes tener un marker o carpeta específica)
                    pytest test/rest-test/test-rest-cd.py --junitxml=reports/rest-readonly-results.xml
                '''
            }
            post {
                always {
                    junit 'reports/rest-readonly-results.xml'
                }
                failure {
                    error("❌ Tests REST solo lectura fallidos.")
                }
            }
        }
    }

    post {
        failure {
            echo "❌ Pipeline CD producción fallido."
        }
        success {
            echo "✅ Pipeline CD producción finalizado correctamente."
        }
    }
}